=== baibhab07/GiftGrab-Digital-Card-Shop/catalog_20049393.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Flat Catalog Design -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="giftgrab">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="mainstore" />
                <xs:element ref="giftcards" />
                <xs:element ref="footer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- mainstore reference - child element of giftgrab element -->
    <xs:element name="mainstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="logo" />
                <xs:element ref="mainstorename" />
                <xs:element ref="address" />
                <xs:element ref="contact" />
                <xs:element ref="website" />
                <xs:element ref="trademark" />
                <xs:element ref="caret" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- references - child elements of mainstore element  -->
    <xs:element name="logo">
        <xs:complexType />
    </xs:element>

    <xs:element name="mainstorename" type="xs:string" />

    <xs:element name="address">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="city" />
                <xs:element ref="country" />
                <xs:element ref="street" />
                <xs:element ref="zipcode" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="city" type="xs:string" />
    <xs:element name="country" type="xs:string" />
    <xs:element name="street" type="xs:string" />
    <xs:element name="zipcode" type="xs:string" />

    <!-- telephone element can occur multiple times -->
    <xs:element name="contact">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="telephone" maxOccurs="2" />
                <xs:element ref="email" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="telephone">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute ref="type" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- using restriction and enumeration list -->
    <xs:attribute name="type">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="mobile"></xs:enumeration>
                <xs:enumeration value="landline"></xs:enumeration>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>

    <xs:element name="email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <!-- using regex pattern in attribute value-->
                <xs:pattern value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9](\.?[\-a-zA-Z0-9]*[a-zA-Z0-9])*" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="website" type="xs:anyURI" />
    <xs:element name="trademark" type="xs:string" />
    <xs:element name="caret" type="xs:string" />

    <!-- giftcards references - child elements of giftgrab element -->
    <!-- giftcard element can occur multiple times -->
    <xs:element name="giftcards">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" />
                <xs:element maxOccurs="unbounded" minOccurs="1" ref="giftcard" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- title references - child element of giftcards element -->
    <xs:element name="title">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="span" />
            </xs:sequence>
            <xs:attribute type="xs:string" name="class" />
        </xs:complexType>
    </xs:element>

    <xs:element name="span" type="xs:string" />

    <!-- giftcard references - child element of giftcards element -->
    <xs:element name="giftcard">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name" />
                <xs:element ref="image" />
                <xs:element ref="brandname" />
                <!-- ratings element is optional -->
                <xs:element minOccurs="0" ref="ratings" />
                <!-- bestseller element is optional -->
                <xs:element minOccurs="0" ref="bestseller" />
                <xs:element ref="cost" />
                <xs:element ref="reedemamount" />
                <!-- redemption element is optional -->
                <xs:element minOccurs="0" ref="redemption" />
                <xs:element ref="quantity" />
                <!-- validity element is optional -->
                <xs:element minOccurs="0" ref="validity" />
                <!-- rank element is optional -->
                <xs:element minOccurs="0" ref="rank" />
                <xs:element ref="features" />
                <xs:element ref="message" />
            </xs:sequence>
            <!-- defining ID datatype on g_id attribute  -->
            <xs:attribute name="g_id" use="required" type="xs:ID" />
            <xs:attribute name="cardType" use="required" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="name">
        <xs:complexType mixed="true">
            <xs:attribute name="ASIN" use="required" type="xs:NMTOKEN" />
        </xs:complexType>
    </xs:element>

    <xs:element name="image">
        <xs:complexType>
            <!-- defining IDREF datatype on i_id attribute  -->
            <xs:attribute name="i_id" use="required" type="xs:IDREF" />
        </xs:complexType>
    </xs:element>

    <xs:element name="brandname" type="xs:string" />
    <xs:element name="ratings" type="xs:string" />
    <xs:element name="bestseller" type="xs:string" />
    <xs:element name="cost" type="xs:string" />
    <xs:element name="reedemamount" type="xs:string" />
    <xs:element name="redemption" type="xs:string" />
    <xs:element name="quantity" type="xs:string" />
    <xs:element name="validity" type="xs:string" />
    <!-- validto references - child element of validity element  -->

    <xs:element name="rank" type="xs:string" />

    <xs:element name="features">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="feature" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- feature reference - child element of features element  -->
    <xs:element name="feature" type="xs:string" />
    <xs:element name="message" type="xs:string" />

    <!-- footer reference - child element of giftgrab element  -->
    <xs:element name="footer">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="copyright" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- copyright reference - child element of footer element  -->
    <xs:element name="copyright"></xs:element>
</xs:schema>

=== baibhab07/GiftGrab-Digital-Card-Shop/catalog_20049393.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- CSS linking -->
<?xml-stylesheet type="text/css" href="catalog_20049393.css"?>

<!-- XML schema linking -->
<giftgrab xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_20049393.xsd">

    <!-- Header of the document, contains information about store including a logo -->
    <mainstore>
        <logo></logo>
        <mainstorename>GiftGrab</mainstorename>
        <address>
            <city>London</city>
            <country>United Kingdom</country>
            <street>Shaftesbury Avenue</street>
            <zipcode>WC2</zipcode>
        </address>
        <contact>
            Contact Us At:
            <telephone type="mobile">441234567901</telephone>
            <telephone type="landline">02476079721</telephone>
            <email>giftgrab2022@gmail.com</email>
        </contact>
        <website>www.gift-grab.com</website>
        <trademark>Delivering Happiness</trademark>
        <caret>V</caret>
    </mainstore>

    <!-- This section contains all the giftcards and their information, acts as body to the document -->
    <giftcards>
        <title class="titleText">
            Available
            <span>G</span>
            iftcards
        </title>

        <!-- Contains information about each giftcard individually inside giftcard -->
        <giftcard g_id="G01" cardType="digital">
            <name ASIN="B078J21W75">Netflix Gift Card</name>
            <image i_id="G01" />
            <brandname>By: Netflix</brandname>
            <ratings>Ratings: 10,887 customer ratings</ratings>
            <bestseller>Bestseller</bestseller>
            <cost>Cost: $30</cost>
            <reedemamount>Reedem Amount: $20</reedemamount>
            <quantity>
                Quantity Available: 4
            </quantity>
            <validity>
                Valid Until: September 16, 2022
            </validity>
            <rank>Rank: #54 in Gift Cards</rank>
            <features>
                Features
                <feature>No credit card required</feature>
                <feature>Cancel anytime</feature>
                <feature>No returns and no refunds</feature>
            </features>
            <message>Your TV shows &#38; movies. Your Way</message>
        </giftcard>


        <giftcard g_id="G02" cardType="digital">
            <name ASIN="B08F3C99KN">Apple Gift Card</name>
            <image i_id="G02" />
            <brandname>By: Apple</brandname>
            <ratings>Ratings: 38,969 customer ratings</ratings>
            <bestseller>Bestseller</bestseller>
            <cost>Cost: $200</cost>
            <reedemamount>Reedem Amount: $150</reedemamount>
            <quantity>
                Quantity Available: 2
            </quantity>
            <validity>
                Valid Until: November 1, 2022
            </validity>
            <rank>Rank: #6 in Gift Cards</rank>
            <features>
                Features
                <feature>For all things Apple - iPad, Airpods, Apple Watch, iPhone, MacBook, iCloud, accessories, and more.</feature>
                <feature>Perfect for App Store purchases and subscription-get apps, games, music, movies, TV shows, and more</feature>
                <feature>The perfect gift to say happy, birthday, thank you, congratulations, and more</feature>
                <feature>To make purchases at an Apple Store location, take the gift card to the Apple Store before redeeming it.</feature>
                <feature>No returns or refunds on Apple Gift Cards. Terms Apply.</feature>
            </features>
            <message>App Store, iTunes, iPhone, iPad, Airpods, MacBook, accessories and more.</message>
        </giftcard>

        <giftcard g_id="G03" cardType="digital">
            <name ASIN="B079YMX2J6">Uber Gift Card</name>
            <image i_id="G03" />
            <brandname>By: Uber</brandname>
            <ratings>Ratings: 17,798 customer ratings</ratings>
            <bestseller>Bestseller</bestseller>
            <cost>Cost: $100</cost>
            <reedemamount>Reedem Amount: $85</reedemamount>
            <quantity>
                Quantity Available: 5
            </quantity>
            <validity>
                Valid Until: December 25, 2022
            </validity>
            <rank>Rank: #41 in Gift Cards</rank>
            <features>
                Features
                <feature>This card is redeemable via the Uber app within the U.K in cities where Uber is available.</feature>
                <feature>Redemption: Mobile App</feature>
                <feature>No returns and refunds on gift cards</feature>
            </features>
            <message>Move the way you want.</message>
        </giftcard>


        <giftcard g_id="G04" cardType="physical" xmlns:sb="https://www.w3schools.com/starbucks">
            <name ASIN="B07ZSB9QYL">Starbucks Gift Card</name>
            <image i_id="G04" />
            <brandname>By: Starbucks</brandname>
            <ratings>Ratings: 18,430 customer ratings</ratings>
            <bestseller>Bestseller</bestseller>
            <cost>Cost: $50</cost>
            <reedemamount>Reedem Amount: $45</reedemamount>
            <redemption>Redemption: Instore</redemption>
            <quantity>
                Quantity Available: 15
            </quantity>
            <validity>
                Valid Until: January 1, 2023
            </validity>
            <rank>Rank: #51 in Gift Cards</rank>
            <features>
                Features
                <feature>Redemption: Instore</feature>
                <feature>No returns and refunds on gift cards</feature>
            </features>
            <message>Brewed for those who love coffee.</message>
        </giftcard>

        <giftcard g_id="G05" cardType="digital">
            <name ASIN="B08MW92TWD">Lyft Gift Card</name>
            <image i_id="G05" />
            <brandname>By: Lyft</brandname>
            <ratings>Ratings: 3,157 customer ratings</ratings>
            <cost>Cost: $90</cost>
            <reedemamount>Reedem Amount: $75</reedemamount>
            <quantity>
                Quantity Available: 10
            </quantity>
            <validity>
                Valid Until: August 15, 2022
            </validity>
            <rank>Rank: #70 in Gift Cards</rank>
            <features>
                Features
                <feature>The perfect gift for holidays, birthdays, anniversaries, friends, family, coworkers, acquaintences, people you sort of like and want to be nice to.</feature>
                <feature>Use it for standard rides, shared rides, fancy cars(!!), bikes, and scooters</feature>
                <feature>We are committed to the community`s well-being and have instituted health and safety guidelines for riders and drivers based on CDC guidance.</feature>
                <feature>Please note: There are no returns or refunds for gift cards.</feature>
            </features>
            <message>Rideshare, bikes, scooters, shared rides, Lyft XL, Lyft Lux, Lux Black, Lux Black XL.</message>
        </giftcard>

        <giftcard g_id="G06" cardType="digital">
            <name ASIN="B08MW92TWD">Spotify Premium 12 Month Subscription Gift Card</name>
            <image i_id="G06" />
            <brandname>By: Spotify</brandname>
            <cost>Cost: $40</cost>
            <reedemamount>Reedem Amount: $30</reedemamount>
            <quantity>
                Quantity Available: 7
            </quantity>
            <validity>
                Valid Until: April 15, 2023
            </validity>
            <rank>Rank: #147 in Gift Cards</rank>
            <features>
                Features
                <feature>Millions of songs and thousands of podcasts. Play on-demand and offline, anywhere.</feature>
                <feature>All your music is ad-free, uninterrupted and in high quality audio.</feature>
                <feature>No returns and no refunds on gift cards.</feature>
            </features>
            <message>Music for every mood. Unlimited music without ads and interference. Hope you enjoy this gift card!</message>
        </giftcard>

        <giftcard g_id="G07" cardType="physical">
            <name ASIN="B074T91QTZ">Dominos Pizza Gift Card</name>
            <image i_id="G07" />
            <brandname>By: Dominos</brandname>
            <ratings>Ratings: 5,167 customer ratings</ratings>
            <cost>Cost: $40</cost>
            <reedemamount>Reedem Amount: $35</reedemamount>
            <redemption>Redemption: Instore</redemption>
            <quantity>
                Quantity Available: 3
            </quantity>
            <validity>
                Valid Until: May 30, 2022
            </validity>
            <rank>Rank: #163 in Gift Cards</rank>
            <features>
                Features
                <feature>Print certificate or provide your 19 digit gift card number and 4 digit pin over the phone, online, or in-store.</feature>
                <feature>Card may only be used for purchases at participating Domino's Pizza stores in the UK.</feature>
                <feature>No returns and no refunds on gift cards.</feature>
            </features>
            <message>Dil, Dosti, Domino's!</message>
        </giftcard>

        <giftcard g_id="G08" cardType="digital">
            <name ASIN="B08MW92TWD">Google Play gift code - give the gift of games, apps and more - US Only</name>
            <image i_id="G08" />
            <brandname>By: Google</brandname>
            <ratings>Ratings: 33,314 customer ratings</ratings>
            <bestseller>Bestseller</bestseller>
            <cost>Cost: $40</cost>
            <reedemamount>Reedem Amount: $35</reedemamount>
            <quantity>
                Quantity Available: 7
            </quantity>
            <validity>
                Valid Until: April 15, 2022
            </validity>
